// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtxvbebfhikvlyfonwdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0eHZiZWJmaGlrdmx5Zm9ud2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzM2MzMsImV4cCI6MjA2OTM0OTYzM30.aFCy0mMfdNRLJNxMykrrHck6rQ_AdhG00WKJCgxepKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});